// Live Polymarket Data Integration
export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  try {
    // Polymarket uses their Gamma API for market data
    // Public API endpoint - no authentication required
    const POLYMARKET_API = 'https://gamma-api.polymarket.com';

    // Fetch active markets
    const marketsResponse = await fetch(`${POLYMARKET_API}/markets?active=true&closed=false&limit=50`, {
      headers: {
        'Accept': 'application/json',
      }
    });

    if (!marketsResponse.ok) {
      throw new Error(`Polymarket API error: ${marketsResponse.status}`);
    }

    const marketsData = await marketsResponse.json();

    // Filter for high-volume markets that Miyomi would care about
    const relevantMarkets = marketsData
      .filter(market => {
        // Filter for markets with significant volume and liquidity
        return market.volume24hr > 10000 || market.liquidity > 50000;
      })
      .map(market => ({
        id: market.id,
        question: market.question,
        description: market.description,
        outcomes: market.outcomes,
        outcomePrices: market.outcomePrices,
        volume24h: market.volume24hr,
        liquidity: market.liquidity,
        endDate: market.endDate,
        tags: market.tags,
        url: `https://polymarket.com/event/${market.slug}`,
        // Add Miyomi's contrarian analysis (would be generated by AI in production)
        miyomiAnalysis: generateContrarianTake(market)
      }))
      .slice(0, 10); // Top 10 markets

    return res.status(200).json({
      success: true,
      source: 'polymarket_live',
      timestamp: new Date().toISOString(),
      markets: relevantMarkets
    });

  } catch (error) {
    console.error('Polymarket API error:', error);

    // Fallback to mock data if API fails
    return res.status(200).json({
      success: false,
      source: 'mock_fallback',
      error: error.message,
      markets: getMockPolymarketData()
    });
  }
}

// Generate contrarian analysis based on market consensus
function generateContrarianTake(market) {
  if (!market.outcomePrices || market.outcomePrices.length < 2) {
    return null;
  }

  const yesPrice = parseFloat(market.outcomePrices[0]);
  const noPrice = parseFloat(market.outcomePrices[1]);

  // Identify extreme consensus (>70% or <30%)
  const extremeConsensus = yesPrice > 0.7 || yesPrice < 0.3;

  if (!extremeConsensus) {
    return null; // Miyomi only takes positions against extreme consensus
  }

  const contrarian = yesPrice > 0.7 ? 'NO' : 'YES';
  const edge = Math.abs(50 - (yesPrice * 100));

  return {
    position: contrarian,
    confidence: Math.min(95, 50 + edge),
    edge: edge,
    thesis: contrarian === 'NO'
      ? `Market at ${Math.round(yesPrice * 100)}% YES shows dangerous consensus. The crowd's certainty is precisely why they're wrong.`
      : `Market at ${Math.round(yesPrice * 100)}% YES shows extreme pessimism. Maximum opportunity when everyone looks the other way.`
  };
}

// Fallback mock data if API fails
function getMockPolymarketData() {
  return [
    {
      id: 'mock-1',
      question: 'Will Bitcoin reach $100,000 by end of 2025?',
      outcomes: ['Yes', 'No'],
      outcomePrices: [0.73, 0.27],
      volume24h: 1245670,
      liquidity: 3456789,
      url: 'https://polymarket.com/mock',
      miyomiAnalysis: {
        position: 'NO',
        confidence: 78,
        edge: 23,
        thesis: 'Extreme bullish consensus at 73% is a classic contrarian signal.'
      }
    }
  ];
}